id: P006789
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 12:23:01.346424
source_metadata:
  id: bdr:W20916
  title: གུ་བཀྲའི་ཆོས་འབྱུང
  author: ''
  volumes:
    5061507347dd492098127e9f71431a0c:
      image_group_id: I5712
      title: ''
      volume_number: 1
      total_pages: 1100
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
