id: P006789
initial_creation_type: ocr
source_metadata:
  id: bdr:W20916
  title: གུ་བཀྲའི་ཆོས་འབྱུང
  author: ''
  volumes:
    5061507347dd492098127e9f71431a0c:
      image_group_id: I5712
      title: ''
      volume_number: 1
      total_pages: 1100
